name: Advanced CI Pipeline

on: 
  push:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 20
      - run: npm install
      - run: npm run build

  test:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - run: npm run test

  deploy:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - run: npm run deploy
